import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
  en: {
    // Common
    'back_to_chat': 'Back to Chat',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'cancel': 'Cancel',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'create': 'Create',
    'update': 'Update',
    'yes': 'Yes',
    'no': 'No',
    
    // Dashboard
    'mood_dashboard': 'Mood Dashboard',
    'mental_wellness_insights': 'Your mental wellness insights at a glance',
    'todays_wri': "Today's WRI",
    'band': 'Band',
    'insight': 'INSIGHT',
    'band_explanation': 'BAND EXPLANATION',
    'trend': 'TREND',
    'top_contributors': 'Top Contributors',
    'wri_trend': 'WRI Trend (Last 30 Entries)',
    'screening_flags': 'Screening Flags',
    'personalized_recommendations': 'Personalized Recommendations',
    'depression': 'Depression',
    'anxiety': 'Anxiety',
    'burnout_strain': 'Burnout Strain',
    'social_isolation': 'Social Isolation',
    'help_readiness': 'Help Readiness',
    'per_chat_wri': 'Per‑chat WRI',
    'daily_wri': 'Daily WRI',
    
    // Journal
    'my_journal': 'My Journal',
    'journal_description': 'Write down your thoughts, feelings, and experiences in your personal space.',
    'your_entries': 'Your Entries',
    'new_entry': 'New Entry',
    'no_journal_entries': 'No journal entries yet. Create your first entry!',
    'create_new_entry': 'Create New Entry',
    'edit_entry': 'Edit Entry',
    'title': 'Title',
    'content': 'Content',
    'enter_journal_title': 'Enter journal title...',
    'write_thoughts': 'Write your thoughts here or use voice recording above...',
    'characters': 'characters',
    'created': 'Created',
    'updated': 'Updated',
    'select_journal_entry': 'Select a journal entry to read',
    'choose_entry_or_create': 'Choose an entry from the list or create a new one to get started.',
    'encrypted': 'Encrypted',
    'auto_clear_30min': '(Auto-clear in 30min)',
    'password_required': 'Password Required',
    'journal_created_success': 'Journal entry created and encrypted successfully! Your mood score will improve! 🎉',
    'journal_updated_success': 'Journal entry updated and encrypted successfully!',
    'journal_deleted_success': 'Journal entry deleted successfully!',
    'enter_password': 'Enter Journal Password',
    'create_password': 'Create Journal Password',
    'encrypted_content': 'Encrypted Content',
    'enter_password_to_view': 'Enter your password to view this journal entry',
    'decrypting_content': 'Decrypting journal content...',
    'please_sign_in_journal': 'Please sign in to access your journal',
    
    // Chat
    'new_chat': 'New Chat',
    'insights': 'Insights',
    'goal_tracker': 'Goal Tracker',
    'personal_assistant': 'Personal Assistant',
    'journaling': 'Journaling',
    'professional_help': 'Professional Help',
    'dashboard': 'Dashboard',
    'chat_placeholder': 'Type your message here...',
    'send': 'Send',
    'voice_recorder': 'Voice Recorder',
    'start_recording': 'Start Recording',
    'stop_recording': 'Stop Recording',
    'recording': 'Recording...',
    'transcribing': 'Transcribing...',
    'please_sign_in_chat': 'Please sign in to start chatting',
    
    // Professional Help
    'professional_help_title': 'Professional Help',
    'find_mental_health_professionals': 'Find mental health professionals near you',
    'search_location': 'Search location...',
    'search': 'Search',
    'no_results': 'No results found',
    'loading_professionals': 'Loading professionals...',
    'please_sign_in_professional': 'Please sign in to access professional help',
    
    // Login
    'welcome': 'Welcome',
    'sign_in_with_google': 'Sign in with Google',
    'sign_in_with_github': 'Sign in with GitHub',
    'sign_in_with_microsoft': 'Sign in with Microsoft',
    'sign_out': 'Sign Out',
    'mental_wellness_platform': 'Mental Wellness Platform',
    'your_mental_health_matters': 'Your mental health matters. Get support, track your mood, and find professional help when you need it.',
    
    // Theme
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    
    // Language
    'language': 'Language',
    'english': 'English',
    'hindi': 'हिंदी',
    'tamil': 'தமிழ்',
    'telugu': 'తెలుగు',
    'kannada': 'ಕನ್ನಡ',
    
    // Additional keys
    'continue_anonymously': 'Continue Anonymously',
    'no_account': 'No Account',
    'find_nearby_help': 'Find Nearby Help',
    'location_permission_message': 'We need your location to find the nearest mental health helpline centers in your area.',
    'getting_location': 'Getting Location...',
    'allow_location_access': 'Allow Location Access',
    
    // Journal specific
    'encrypted_journal_entry': 'Encrypted Journal Entry',
    'create_journal_password': 'Create Journal Password',
    'confirm_password': 'Confirm Password',
    'password_security_note': 'Your password is never sent to the server',
    'password_local_note': 'It\'s used locally to encrypt your data',
    'password_remember_note': 'Remember this password - it can\'t be recovered!',
    
    // Date and time
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'am': 'AM',
    'pm': 'PM',
    
    // Chat specific
    'your_mental_wellness_companion': 'Your mental wellness companion',
    'ai_powered_private_secure': 'AI-Powered • Private • Secure',
    'or_continue_with': 'Or continue with',
    'by_continuing_you_agree': 'By continuing, you agree to our',
    'privacy_policy': 'Privacy Policy',
    'and': 'and',
    'terms_of_service': 'Terms of Service',
    'your_privacy_is_protected': 'Your Privacy is Protected',
    'new_chat_session_started': '🆕 New Chat Session Started',
    'previous_insights_displayed': 'Previous insights are displayed but not used for AI decisions',
    'wellness_insights': 'Wellness Insights',
    'stored_insights_previous_sessions': '💾 Stored Insights (Previous Sessions)',
    'type_your_message_here': 'Type your message here...',
    'please_sign_in_to_start_chatting': 'Please sign in to start chatting',
    
    // Professional Help Page
    'available_247_support': 'Available 24/7 mental health support in your area',
    'location_label': 'Location',
    'call_for_help': 'Call for Help',
    'visit_website': 'Visit Website',
    'contact_number': 'Contact Number',
    'specialties': 'Specialties',
    'available_247': 'Available 24/7',
    'km_away': 'km away',
    'geolocation_not_supported': 'Geolocation is not supported by this browser',
    'failed_to_get_location': 'Failed to get location permission',
    'failed_to_fetch_helplines': 'Failed to fetch nearby helpline centers',
    
    // Hobbies Pages
    'hobbies_recommendations': 'Hobbies Recommendations',
    'discover_new_hobbies': 'Discover new hobbies and activities tailored for you',
    'recommended_for_you': 'Recommended for You',
    'online_courses': 'Online Courses',
    'local_events': 'Local Events',
    'hobby_name': 'Hobby Name',
    'difficulty_level': 'Difficulty Level',
    'time_required': 'Time Required',
    'benefits': 'Benefits',
    'get_started': 'Get Started',
    'course_title': 'Course Title',
    'platform': 'Platform',
    'duration': 'Duration',
    'rating': 'Rating',
    'enroll_now': 'Enroll Now',
    'event_name': 'Event Name',
    'date': 'Date',
    'location': 'Location',
    'register': 'Register',
    
    // Meditation & Yoga
    'meditation_yoga': 'Meditation & Yoga',
    'find_peace_balance': 'Find your inner peace and balance',
    'meditation_videos': 'Meditation Videos',
    'meditation_sounds': 'Meditation Sounds',
    'yoga_poses': 'Yoga Poses',
    'guided_meditation': 'Guided Meditation',
    'breathing_exercises': 'Breathing Exercises',
    'relaxation_techniques': 'Relaxation Techniques',
    'play': 'Play',
    'pause': 'Pause',
    'minutes': 'minutes',
    'watch_video': 'Watch Video',
    'listen_now': 'Listen Now',
    
    // Goals & Tracker
    'goal_tracker_title': 'Goal Tracker',
    'track_your_progress': 'Track your progress towards wellness goals',
    'daily_goals': 'Daily Goals',
    'weekly_goals': 'Weekly Goals',
    'monthly_goals': 'Monthly Goals',
    'add_goal': 'Add Goal',
    'goal_description': 'Goal Description',
    'target_date': 'Target Date',
    'progress': 'Progress',
    'completed': 'Completed',
    'in_progress': 'In Progress',
    'not_started': 'Not Started',
    'mark_complete': 'Mark as Complete',
    'edit_goal': 'Edit Goal',
    'delete_goal': 'Delete Goal',
    
    // Personal Assistant
    'personal_assistant_title': 'Personal Assistant',
    'your_ai_wellness_assistant': 'Your AI-powered wellness assistant',
    'ask_me_anything': 'Ask me anything about your wellness journey',
    'suggestions': 'Suggestions',
    'morning_routine': 'Morning Routine',
    'stress_management': 'Stress Management',
    'sleep_tips': 'Sleep Tips',
    'healthy_habits': 'Healthy Habits',
    
    // Insights Page
    'insights_title': 'Insights',
    'your_wellness_journey': 'Your wellness journey insights',
    'mood_trends': 'Mood Trends',
    'sleep_patterns': 'Sleep Patterns',
    'stress_levels': 'Stress Levels',
    'activity_log': 'Activity Log',
    'weekly_summary': 'Weekly Summary',
    'monthly_summary': 'Monthly Summary',
    'export_data': 'Export Data',
    'view_details': 'View Details',
    'last_7_days': 'Last 7 Days',
    'last_30_days': 'Last 30 Days',
    'last_90_days': 'Last 90 Days',
    'all_time': 'All Time',
    'by': 'By',
    
    // Hobbies Survey
    'discover_your_hobbies': 'Discover Your Hobbies',
    'tell_us_interests': 'Tell us about your interests and we\'ll help you find the perfect activities',
    'what_interests_you': 'What interests you? (Select multiple)',
    'whats_your_budget': 'What\'s your budget?',
    'when_available': 'When are you available?',
    'your_location': 'Your Location',
    'use_current_location': 'Use Current Location',
    'or_enter_city': 'Or enter your city manually',
    'city_placeholder': 'Enter your city',
    'get_recommendations': 'Get Personalized Recommendations',
    'select_at_least_one': 'Please select at least one hobby',
    'provide_location': 'Please provide your location',
    'user_not_authenticated': 'User not authenticated',
    'geolocation_not_supported_browser': 'Geolocation is not supported by your browser',
    'error_getting_location': 'Error getting location',
    'day_streak': 'Day Streak!',
    'meditation_and_yoga': 'Meditation & Yoga',
    'hobbies_and_wanderlust': 'Hobbies & Wanderlust',
    'logout': 'Logout',
    'guest_user': 'Guest User',
    'anonymous': 'Anonymous',
    'secure': 'Secure',
    'anonymous_session': 'Anonymous Session',
    'tips_for_better_practice': '💡 Tips for Better Practice',
    'for_meditation': 'For Meditation:',
    'for_sounds': 'For Sounds:',
    'find_quiet_space': 'Find a quiet, comfortable space',
    'start_shorter_sessions': 'Start with shorter sessions (5-10 minutes)',
    'focus_breathing': 'Focus on your breathing',
    'be_patient': 'Be patient with yourself',
    'use_headphones': 'Use headphones for better immersion',
    'adjust_volume': 'Adjust volume to comfortable levels',
    'combine_breathing': 'Combine with breathing exercises',
    'create_practice_space': 'Create a dedicated practice space',
  },
  hi: {
    // Common
    'back_to_chat': 'चैट पर वापस जाएं',
    'loading': 'लोड हो रहा है...',
    'error': 'त्रुटि',
    'success': 'सफलता',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'create': 'बनाएं',
    'update': 'अपडेट करें',
    'yes': 'हाँ',
    'no': 'नहीं',
    
    // Dashboard
    'mood_dashboard': 'मूड डैशबोर्ड',
    'mental_wellness_insights': 'आपकी मानसिक स्वास्थ्य अंतर्दृष्टि एक नज़र में',
    'todays_wri': 'आज का WRI',
    'band': 'बैंड',
    'insight': 'अंतर्दृष्टि',
    'band_explanation': 'बैंड स्पष्टीकरण',
    'trend': 'ट्रेंड',
    'top_contributors': 'शीर्ष योगदानकर्ता',
    'wri_trend': 'WRI ट्रेंड (अंतिम 30 प्रविष्टियां)',
    'screening_flags': 'स्क्रीनिंग फ्लैग्स',
    'personalized_recommendations': 'व्यक्तिगत सुझाव',
    'depression': 'अवसाद',
    'anxiety': 'चिंता',
    'burnout_strain': 'बर्नआउट तनाव',
    'social_isolation': 'सामाजिक अलगाव',
    'help_readiness': 'सहायता तत्परता',
    'per_chat_wri': 'प्रति-चैट WRI',
    'daily_wri': 'दैनिक WRI',
    
    // Journal
    'my_journal': 'मेरी डायरी',
    'journal_description': 'अपने विचार, भावनाएं और अनुभव अपने व्यक्तिगत स्थान में लिखें।',
    'your_entries': 'आपकी प्रविष्टियां',
    'new_entry': 'नई प्रविष्टि',
    'no_journal_entries': 'अभी तक कोई डायरी प्रविष्टि नहीं। अपनी पहली प्रविष्टि बनाएं!',
    'create_new_entry': 'नई प्रविष्टि बनाएं',
    'edit_entry': 'प्रविष्टि संपादित करें',
    'title': 'शीर्षक',
    'content': 'सामग्री',
    'enter_journal_title': 'डायरी शीर्षक दर्ज करें...',
    'write_thoughts': 'अपने विचार यहाँ लिखें या ऊपर वॉइस रिकॉर्डिंग का उपयोग करें...',
    'characters': 'वर्ण',
    'created': 'बनाया गया',
    'updated': 'अपडेट किया गया',
    'select_journal_entry': 'पढ़ने के लिए एक डायरी प्रविष्टि चुनें',
    'choose_entry_or_create': 'सूची से एक प्रविष्टि चुनें या शुरू करने के लिए एक नई बनाएं।',
    'encrypted': 'एन्क्रिप्टेड',
    'auto_clear_30min': '(30 मिनट में ऑटो-क्लियर)',
    'password_required': 'पासवर्ड आवश्यक',
    'journal_created_success': 'डायरी प्रविष्टि सफलतापूर्वक बनाई और एन्क्रिप्ट की गई! आपका मूड स्कोर सुधरेगा! 🎉',
    'journal_updated_success': 'डायरी प्रविष्टि सफलतापूर्वक अपडेट और एन्क्रिप्ट की गई!',
    'journal_deleted_success': 'डायरी प्रविष्टि सफलतापूर्वक हटाई गई!',
    'enter_password': 'डायरी पासवर्ड दर्ज करें',
    'create_password': 'डायरी पासवर्ड बनाएं',
    'encrypted_content': 'एन्क्रिप्टेड सामग्री',
    'enter_password_to_view': 'इस डायरी प्रविष्टि को देखने के लिए अपना पासवर्ड दर्ज करें',
    'decrypting_content': 'डायरी सामग्री डिक्रिप्ट हो रही है...',
    'please_sign_in_journal': 'अपनी डायरी तक पहुंचने के लिए कृपया साइन इन करें',
    
    // Chat
    'new_chat': 'नई चैट',
    'insights': 'अंतर्दृष्टि',
    'goal_tracker': 'लक्ष्य ट्रैकर',
    'personal_assistant': 'पर्सनल असिस्टेंट',
    'journaling': 'डायरी लेखन',
    'professional_help': 'व्यावसायिक सहायता',
    'dashboard': 'डैशबोर्ड',
    'chat_placeholder': 'अपना संदेश यहाँ टाइप करें...',
    'send': 'भेजें',
    'voice_recorder': 'वॉइस रिकॉर्डर',
    'start_recording': 'रिकॉर्डिंग शुरू करें',
    'stop_recording': 'रिकॉर्डिंग रोकें',
    'recording': 'रिकॉर्डिंग...',
    'transcribing': 'ट्रांसक्राइब हो रहा है...',
    'please_sign_in_chat': 'चैटिंग शुरू करने के लिए कृपया साइन इन करें',
    
    // Professional Help
    'professional_help_title': 'व्यावसायिक सहायता',
    'find_mental_health_professionals': 'अपने पास मानसिक स्वास्थ्य पेशेवरों को खोजें',
    'search_location': 'स्थान खोजें...',
    'search': 'खोजें',
    'no_results': 'कोई परिणाम नहीं मिला',
    'loading_professionals': 'पेशेवरों को लोड कर रहे हैं...',
    'please_sign_in_professional': 'व्यावसायिक सहायता तक पहुंचने के लिए कृपया साइन इन करें',
    
    // Login
    'welcome': 'स्वागत है',
    'sign_in_with_google': 'Google के साथ साइन इन करें',
    'sign_in_with_github': 'GitHub के साथ साइन इन करें',
    'sign_in_with_microsoft': 'Microsoft के साथ साइन इन करें',
    'sign_out': 'साइन आउट',
    'mental_wellness_platform': 'मानसिक स्वास्थ्य प्लेटफॉर्म',
    'your_mental_health_matters': 'आपका मानसिक स्वास्थ्य मायने रखता है। समर्थन प्राप्त करें, अपने मूड को ट्रैक करें, और जरूरत पड़ने पर व्यावसायिक सहायता खोजें।',
    
    // Theme
    'light_mode': 'लाइट मोड',
    'dark_mode': 'डार्क मोड',
    
    // Language
    'language': 'भाषा',
    'english': 'English',
    'hindi': 'हिंदी',
    
    // Additional keys
    'continue_anonymously': 'बिना खाते के जारी रखें',
    'no_account': 'कोई खाता नहीं',
    'find_nearby_help': 'पास में सहायता खोजें',
    'location_permission_message': 'आपके क्षेत्र में निकटतम मानसिक स्वास्थ्य हेल्पलाइन केंद्र खोजने के लिए हमें आपका स्थान चाहिए।',
    'getting_location': 'स्थान प्राप्त कर रहे हैं...',
    'allow_location_access': 'स्थान पहुंच की अनुमति दें',
    
    // Journal specific
    'encrypted_journal_entry': 'एन्क्रिप्टेड डायरी प्रविष्टि',
    'create_journal_password': 'डायरी पासवर्ड बनाएं',
    'confirm_password': 'पासवर्ड की पुष्टि करें',
    'password_security_note': 'आपका पासवर्ड कभी सर्वर पर नहीं भेजा जाता',
    'password_local_note': 'यह स्थानीय रूप से आपके डेटा को एन्क्रिप्ट करने के लिए उपयोग किया जाता है',
    'password_remember_note': 'इस पासवर्ड को याद रखें - इसे पुनर्प्राप्त नहीं किया जा सकता!',
    
    // Date and time
    'january': 'जनवरी',
    'february': 'फरवरी',
    'march': 'मार्च',
    'april': 'अप्रैल',
    'may': 'मई',
    'june': 'जून',
    'july': 'जुलाई',
    'august': 'अगस्त',
    'september': 'सितंबर',
    'october': 'अक्टूबर',
    'november': 'नवंबर',
    'december': 'दिसंबर',
    'am': 'पूर्वाह्न',
    'pm': 'अपराह्न',
    
    // Chat specific
    'your_mental_wellness_companion': 'आपका मानसिक स्वास्थ्य साथी',
    'ai_powered_private_secure': 'AI-संचालित • निजी • सुरक्षित',
    'or_continue_with': 'या इसके साथ जारी रखें',
    'by_continuing_you_agree': 'जारी रखकर, आप हमारी',
    'privacy_policy': 'गोपनीयता नीति',
    'and': 'और',
    'terms_of_service': 'सेवा की शर्तें',
    'your_privacy_is_protected': 'आपकी गोपनीयता सुरक्षित है',
    'new_chat_session_started': '🆕 नई चैट सत्र शुरू हुआ',
    'previous_insights_displayed': 'पिछली अंतर्दृष्टि प्रदर्शित की गई है लेकिन AI निर्णयों के लिए उपयोग नहीं की जाती',
    'wellness_insights': 'कल्याण अंतर्दृष्टि',
    'stored_insights_previous_sessions': '💾 संग्रहीत अंतर्दृष्टि (पिछले सत्र)',
    'type_your_message_here': 'अपना संदेश यहाँ टाइप करें...',
    'please_sign_in_to_start_chatting': 'चैटिंग शुरू करने के लिए कृपया साइन इन करें',
    
    // Professional Help Page
    'available_247_support': 'आपके क्षेत्र में 24/7 मानसिक स्वास्थ्य सहायता उपलब्ध',
    'location_label': 'स्थान',
    'call_for_help': 'सहायता के लिए कॉल करें',
    'visit_website': 'वेबसाइट पर जाएं',
    'contact_number': 'संपर्क नंबर',
    'specialties': 'विशेषताएं',
    'available_247': '24/7 उपलब्ध',
    'km_away': 'किमी दूर',
    'geolocation_not_supported': 'यह ब्राउज़र जियोलोकेशन को सपोर्ट नहीं करता',
    'failed_to_get_location': 'स्थान अनुमति प्राप्त करने में विफल',
    'failed_to_fetch_helplines': 'पास के हेल्पलाइन केंद्र लाने में विफल',
    
    // Hobbies Pages
    'hobbies_recommendations': 'शौक सिफारिशें',
    'discover_new_hobbies': 'अपने लिए तैयार नए शौक और गतिविधियां खोजें',
    'recommended_for_you': 'आपके लिए अनुशंसित',
    'online_courses': 'ऑनलाइन पाठ्यक्रम',
    'local_events': 'स्थानीय कार्यक्रम',
    'hobby_name': 'शौक का नाम',
    'difficulty_level': 'कठिनाई स्तर',
    'time_required': 'आवश्यक समय',
    'benefits': 'लाभ',
    'get_started': 'शुरू करें',
    'course_title': 'पाठ्यक्रम शीर्षक',
    'platform': 'प्लेटफॉर्म',
    'duration': 'अवधि',
    'rating': 'रेटिंग',
    'enroll_now': 'अभी नामांकन करें',
    'event_name': 'कार्यक्रम का नाम',
    'date': 'तारीख',
    'location': 'स्थान',
    'register': 'पंजीकरण करें',
    
    // Meditation & Yoga
    'meditation_yoga': 'ध्यान और योग',
    'find_peace_balance': 'अपनी आंतरिक शांति और संतुलन खोजें',
    'meditation_videos': 'ध्यान वीडियो',
    'meditation_sounds': 'ध्यान ध्वनियां',
    'yoga_poses': 'योग मुद्राएं',
    'guided_meditation': 'निर्देशित ध्यान',
    'breathing_exercises': 'सांस लेने के व्यायाम',
    'relaxation_techniques': 'विश्राम तकनीकें',
    'play': 'चलाएं',
    'pause': 'रोकें',
    'minutes': 'मिनट',
    'watch_video': 'वीडियो देखें',
    'listen_now': 'अभी सुनें',
    
    // Goals & Tracker
    'goal_tracker_title': 'लक्ष्य ट्रैकर',
    'track_your_progress': 'कल्याण लक्ष्यों की ओर अपनी प्रगति को ट्रैक करें',
    'daily_goals': 'दैनिक लक्ष्य',
    'weekly_goals': 'साप्ताहिक लक्ष्य',
    'monthly_goals': 'मासिक लक्ष्य',
    'add_goal': 'लक्ष्य जोड़ें',
    'goal_description': 'लक्ष्य विवरण',
    'target_date': 'लक्ष्य तिथि',
    'progress': 'प्रगति',
    'completed': 'पूर्ण',
    'in_progress': 'प्रगति में',
    'not_started': 'शुरू नहीं हुआ',
    'mark_complete': 'पूर्ण के रूप में चिह्नित करें',
    'edit_goal': 'लक्ष्य संपादित करें',
    'delete_goal': 'लक्ष्य हटाएं',
    
    // Personal Assistant
    'personal_assistant_title': 'व्यक्तिगत सहायक',
    'your_ai_wellness_assistant': 'आपका AI-संचालित कल्याण सहायक',
    'ask_me_anything': 'अपनी कल्याण यात्रा के बारे में मुझसे कुछ भी पूछें',
    'suggestions': 'सुझाव',
    'morning_routine': 'सुबह की दिनचर्या',
    'stress_management': 'तनाव प्रबंधन',
    'sleep_tips': 'नींद के टिप्स',
    'healthy_habits': 'स्वस्थ आदतें',
    
    // Insights Page
    'insights_title': 'अंतर्दृष्टि',
    'your_wellness_journey': 'आपकी कल्याण यात्रा अंतर्दृष्टि',
    'mood_trends': 'मूड रुझान',
    'sleep_patterns': 'नींद के पैटर्न',
    'stress_levels': 'तनाव स्तर',
    'activity_log': 'गतिविधि लॉग',
    'weekly_summary': 'साप्ताहिक सारांश',
    'monthly_summary': 'मासिक सारांश',
    'export_data': 'डेटा निर्यात करें',
    'view_details': 'विवरण देखें',
    'last_7_days': 'पिछले 7 दिन',
    'last_30_days': 'पिछले 30 दिन',
    'last_90_days': 'पिछले 90 दिन',
    'all_time': 'सभी समय',
    'by': 'द्वारा',
    
    // Hobbies Survey
    'discover_your_hobbies': 'अपने शौक खोजें',
    'tell_us_interests': 'हमें अपनी रुचियों के बारे में बताएं और हम आपको सही गतिविधियां खोजने में मदद करेंगे',
    'what_interests_you': 'आपकी रुचि किसमें है? (एक से अधिक चुनें)',
    'whats_your_budget': 'आपका बजट क्या है?',
    'when_available': 'आप कब उपलब्ध हैं?',
    'your_location': 'आपका स्थान',
    'use_current_location': 'वर्तमान स्थान का उपयोग करें',
    'or_enter_city': 'या अपना शहर मैन्युअल रूप से दर्ज करें',
    'city_placeholder': 'अपना शहर दर्ज करें',
    'get_recommendations': 'व्यक्तिगत सिफारिशें प्राप्त करें',
    'select_at_least_one': 'कृपया कम से कम एक शौक चुनें',
    'provide_location': 'कृपया अपना स्थान प्रदान करें',
    'user_not_authenticated': 'उपयोगकर्ता प्रमाणित नहीं है',
    'geolocation_not_supported_browser': 'जियोलोकेशन इस ब्राउज़र द्वारा समर्थित नहीं है',
    'error_getting_location': 'स्थान प्राप्त करने में त्रुटि',
    'day_streak': 'दिन की लकीर!',
    'meditation_and_yoga': 'ध्यान और योग',
    'hobbies_and_wanderlust': 'शौक और घूमना',
    'logout': 'लॉगआउट',
    'guest_user': 'अतिथि उपयोगकर्ता',
    'anonymous': 'गुमनाम',
    'secure': 'सुरक्षित',
    'anonymous_session': 'गुमनाम सत्र',
    'tips_for_better_practice': '💡 बेहतर अभ्यास के लिए सुझाव',
    'for_meditation': 'ध्यान के लिए:',
    'for_sounds': 'ध्वनियों के लिए:',
    'find_quiet_space': 'एक शांत, आरामदायक जगह खोजें',
    'start_shorter_sessions': 'छोटे सत्रों से शुरू करें (5-10 मिनट)',
    'focus_breathing': 'अपनी सांसों पर ध्यान दें',
    'be_patient': 'अपने साथ धैर्य रखें',
    'use_headphones': 'बेहतर अनुभव के लिए हेडफ़ोन का उपयोग करें',
    'adjust_volume': 'आरामदायक स्तर पर वॉल्यूम समायोजित करें',
    'combine_breathing': 'सांस लेने के व्यायाम के साथ मिलाएं',
    'create_practice_space': 'एक समर्पित अभ्यास स्थान बनाएं',
  },
  ta: {
    // Common
    'back_to_chat': 'அரட்டைக்கு திரும்பு',
    'loading': 'ஏற்றுகிறது...',
    'error': 'பிழை',
    'success': 'வெற்றி',
    'cancel': 'ரத்து செய்',
    'save': 'சேமி',
    'edit': 'திருத்து',
    'delete': 'நீக்கு',
    'create': 'உருவாக்கு',
    'update': 'புதுப்பி',
    'yes': 'ஆம்',
    'no': 'இல்லை',
    
    // Dashboard
    'mood_dashboard': 'மனநிலை டாஷ்போர்டு',
    'mental_wellness_insights': 'உங்கள் மன நல நுண்ணறிவுகள் ஒரே பார்வையில்',
    'todays_wri': 'இன்றைய WRI',
    'band': 'பேண்ட்',
    'insight': 'நுண்ணறிவு',
    'band_explanation': 'பேண்ட் விளக்கம்',
    'trend': 'போக்கு',
    'top_contributors': 'முக்கிய பங்களிப்பாளர்கள்',
    'wri_trend': 'WRI போக்கு (கடைசி 30 உள்ளீடுகள்)',
    'screening_flags': 'ஸ்கிரீனிங் கொடிகள்',
    'personalized_recommendations': 'தனிப்பயனாக்கப்பட்ட பரிந்துரைகள்',
    'depression': 'மனஅழுத்தம்',
    'anxiety': 'பதட்டம்',
    'burnout_strain': 'சோர்வு அழுத்தம்',
    'social_isolation': 'சமூக தனிமை',
    'help_readiness': 'உதவி தயார்நிலை',
    'per_chat_wri': 'ஒரு அரட்டை WRI',
    'daily_wri': 'தினசரி WRI',
    
    // Journal
    'my_journal': 'என் நாட்குறிப்பு',
    'journal_description': 'உங்கள் எண்ணங்கள், உணர்வுகள் மற்றும் அனுபவங்களை உங்கள் தனிப்பட்ட இடத்தில் எழுதுங்கள்.',
    'your_entries': 'உங்கள் உள்ளீடுகள்',
    'new_entry': 'புதிய உள்ளீடு',
    'no_journal_entries': 'இன்னும் நாட்குறிப்பு உள்ளீடுகள் இல்லை. உங்கள் முதல் உள்ளீட்டை உருவாக்குங்கள்!',
    'create_new_entry': 'புதிய உள்ளீட்டை உருவாக்கு',
    'edit_entry': 'உள்ளீட்டைத் திருத்து',
    'title': 'தலைப்பு',
    'content': 'உள்ளடக்கம்',
    'enter_journal_title': 'நாட்குறிப்பு தலைப்பை உள்ளிடவும்...',
    'write_thoughts': 'உங்கள் எண்ணங்களை இங்கே எழுதவும் அல்லது மேலே குரல் பதிவைப் பயன்படுத்தவும்...',
    'characters': 'எழுத்துக்கள்',
    'created': 'உருவாக்கப்பட்டது',
    'updated': 'புதுப்பிக்கப்பட்டது',
    'select_journal_entry': 'படிக்க ஒரு நாட்குறிப்பு உள்ளீட்டைத் தேர்ந்தெடுக்கவும்',
    'choose_entry_or_create': 'பட்டியலிலிருந்து ஒரு உள்ளீட்டைத் தேர்வு செய்யவும் அல்லது தொடங்க புதியதை உருவாக்கவும்.',
    'encrypted': 'மறைக்குறியீடு செய்யப்பட்டது',
    'auto_clear_30min': '(30 நிமிடங்களில் தானாக அழிக்கப்படும்)',
    'password_required': 'கடவுச்சொல் தேவை',
    'journal_created_success': 'நாட்குறிப்பு உள்ளீடு வெற்றிகரமாக உருவாக்கப்பட்டு மறைக்குறியீடு செய்யப்பட்டது! உங்கள் மனநிலை மதிப்பெண் மேம்படும்! 🎉',
    'journal_updated_success': 'நாட்குறிப்பு உள்ளீடு வெற்றிகரமாக புதுப்பிக்கப்பட்டு மறைக்குறியீடு செய்யப்பட்டது!',
    'journal_deleted_success': 'நாட்குறிப்பு உள்ளீடு வெற்றிகரமாக நீக்கப்பட்டது!',
    'enter_password': 'நாட்குறிப்பு கடவுச்சொல்லை உள்ளிடவும்',
    'create_password': 'நாட்குறிப்பு கடவுச்சொல்லை உருவாக்கவும்',
    'encrypted_content': 'மறைக்குறியீடு செய்யப்பட்ட உள்ளடக்கம்',
    'enter_password_to_view': 'இந்த நாட்குறிப்பு உள்ளீட்டைக் காண உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'decrypting_content': 'நாட்குறிப்பு உள்ளடக்கம் மறைக்குறியீடு நீக்கப்படுகிறது...',
    'please_sign_in_journal': 'உங்கள் நாட்குறிப்பை அணுக தயவுசெய்து உள்நுழையவும்',
    
    // Chat
    'new_chat': 'புதிய அரட்டை',
    'insights': 'நுண்ணறிவுகள்',
    'goal_tracker': 'இலக்கு கண்காணிப்பு',
    'personal_assistant': 'தனிப்பட்ட உதவியாளர்',
    'journaling': 'நாட்குறிப்பு எழுதுதல்',
    'professional_help': 'தொழில்முறை உதவி',
    'dashboard': 'டாஷ்போர்டு',
    'chat_placeholder': 'உங்கள் செய்தியை இங்கே தட்டச்சு செய்யவும்...',
    'send': 'அனுப்பு',
    'voice_recorder': 'குரல் பதிவி',
    'start_recording': 'பதிவை தொடங்கு',
    'stop_recording': 'பதிவை நிறுத்து',
    'recording': 'பதிவு செய்கிறது...',
    'transcribing': 'படியெடுக்கிறது...',
    'please_sign_in_chat': 'அரட்டை தொடங்க தயவுசெய்து உள்நுழையவும்',
    
    // Professional Help
    'professional_help_title': 'தொழில்முறை உதவி',
    'find_mental_health_professionals': 'உங்களுக்கு அருகில் மன சுகாதார நிபுணர்களைக் கண்டறியவும்',
    'search_location': 'இடத்தைத் தேடு...',
    'search': 'தேடு',
    'no_results': 'முடிவுகள் இல்லை',
    'loading_professionals': 'நிபுணர்களை ஏற்றுகிறது...',
    'please_sign_in_professional': 'தொழில்முறை உதவியை அணுக தயவுசெய்து உள்நுழையவும்',
    
    // Login
    'welcome': 'வரவேற்பு',
    'sign_in_with_google': 'Google உடன் உள்நுழையவும்',
    'sign_in_with_github': 'GitHub உடன் உள்நுழையவும்',
    'sign_in_with_microsoft': 'Microsoft உடன் உள்நுழையவும்',
    'sign_out': 'வெளியேறு',
    'mental_wellness_platform': 'மன நல மேடை',
    'your_mental_health_matters': 'உங்கள் மன ஆரோக்கியம் முக்கியம். ஆதரவைப் பெறுங்கள், உங்கள் மனநிலையைக் கண்காணிக்கவும், தேவைப்படும்போது தொழில்முறை உதவியைக் கண்டறியவும்.',
    
    // Theme
    'light_mode': 'ஒளி பயன்முறை',
    'dark_mode': 'இருண்ட பயன்முறை',
    
    // Language
    'language': 'மொழி',
    'english': 'English',
    'hindi': 'हिंदी',
    'tamil': 'தமிழ்',
    'telugu': 'తెలుగు',
    'kannada': 'ಕನ್ನಡ',
    
    // Additional keys
    'continue_anonymously': 'அநாமதேயமாக தொடரவும்',
    'no_account': 'கணக்கு இல்லை',
    'find_nearby_help': 'அருகிலுள்ள உதவியைக் கண்டறியவும்',
    'location_permission_message': 'உங்கள் பகுதியில் அருகிலுள்ள மன சுகாதார உதவி மையங்களைக் கண்டறிய எங்களுக்கு உங்கள் இருப்பிடம் தேவை.',
    'getting_location': 'இருப்பிடத்தைப் பெறுகிறது...',
    'allow_location_access': 'இருப்பிட அணுகலை அனுமதிக்கவும்',
    
    // Journal specific
    'encrypted_journal_entry': 'மறைக்குறியீடு செய்யப்பட்ட நாட்குறிப்பு உள்ளீடு',
    'create_journal_password': 'நாட்குறிப்பு கடவுச்சொல்லை உருவாக்கவும்',
    'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    'password_security_note': 'உங்கள் கடவுச்சொல் ஒருபோதும் சேவையகத்திற்கு அனுப்பப்படாது',
    'password_local_note': 'உங்கள் தரவை உள்ளூர் மறைக்குறியீடு செய்ய இது பயன்படுத்தப்படுகிறது',
    'password_remember_note': 'இந்த கடவுச்சொல்லை நினைவில் வைத்துக் கொள்ளுங்கள் - இதை மீட்டெடுக்க முடியாது!',
    
    // Date and time
    'january': 'ஜனவரி',
    'february': 'பிப்ரவரி',
    'march': 'மார்ச்',
    'april': 'ஏப்ரல்',
    'may': 'மே',
    'june': 'ஜூன்',
    'july': 'ஜூலை',
    'august': 'ஆகஸ்ட்',
    'september': 'செப்டம்பர்',
    'october': 'அக்டோபர்',
    'november': 'நவம்பர்',
    'december': 'டிசம்பர்',
    'am': 'காலை',
    'pm': 'மாலை',
    
    // Chat specific
    'your_mental_wellness_companion': 'உங்கள் மன நல துணை',
    'ai_powered_private_secure': 'AI-இயங்கும் • தனிப்பட்ட • பாதுகாப்பான',
    'or_continue_with': 'அல்லது இதனுடன் தொடரவும்',
    'by_continuing_you_agree': 'தொடர்வதன் மூலம், நீங்கள் எங்கள்',
    'privacy_policy': 'தனியுரிமைக் கொள்கை',
    'and': 'மற்றும்',
    'terms_of_service': 'சேவை விதிமுறைகள்',
    'your_privacy_is_protected': 'உங்கள் தனியுரிமை பாதுகாக்கப்படுகிறது',
    'new_chat_session_started': '🆕 புதிய அரட்டை அமர்வு தொடங்கியது',
    'previous_insights_displayed': 'முந்தைய நுண்ணறிவுகள் காட்டப்படுகின்றன ஆனால் AI முடிவுகளுக்கு பயன்படுத்தப்படவில்லை',
    'wellness_insights': 'நல்வாழ்வு நுண்ணறிவுகள்',
    'stored_insights_previous_sessions': '💾 சேமிக்கப்பட்ட நுண்ணறிவுகள் (முந்தைய அமர்வுகள்)',
    'type_your_message_here': 'உங்கள் செய்தியை இங்கே தட்டச்சு செய்யவும்...',
    'please_sign_in_to_start_chatting': 'அரட்டை தொடங்க தயவுசெய்து உள்நுழையவும்',
    
    // Professional Help Page
    'available_247_support': 'உங்கள் பகுதியில் 24/7 மன சுகாதார ஆதரவு கிடைக்கும்',
    'location_label': 'இடம்',
    'call_for_help': 'உதவிக்கு அழைக்கவும்',
    'visit_website': 'வலைத்தளத்தைப் பார்வையிடவும்',
    'contact_number': 'தொடர்பு எண்',
    'specialties': 'சிறப்புகள்',
    'available_247': '24/7 கிடைக்கும்',
    'km_away': 'கி.மீ தொலைவில்',
    'geolocation_not_supported': 'இந்த உலாவி ஜியோலொகேஷனை ஆதரிக்கவில்லை',
    'failed_to_get_location': 'இருப்பிட அனுமதி பெற முடியவில்லை',
    'failed_to_fetch_helplines': 'அருகிலுள்ள உதவி மையங்களைப் பெற முடியவில்லை',
    
    // Hobbies Pages
    'hobbies_recommendations': 'பொழுதுபோக்கு பரிந்துரைகள்',
    'discover_new_hobbies': 'உங்களுக்காக வடிவமைக்கப்பட்ட புதிய பொழுதுபோக்குகளைக் கண்டறியவும்',
    'recommended_for_you': 'உங்களுக்கு பரிந்துரைக்கப்பட்டது',
    'online_courses': 'ஆன்லைன் படிப்புகள்',
    'local_events': 'உள்ளூர் நிகழ்வுகள்',
    'hobby_name': 'பொழுதுபோக்கு பெயர்',
    'difficulty_level': 'சிரம நிலை',
    'time_required': 'தேவைப்படும் நேரம்',
    'benefits': 'நன்மைகள்',
    'get_started': 'தொடங்குங்கள்',
    'course_title': 'படிப்பு தலைப்பு',
    'platform': 'மேடை',
    'duration': 'காலம்',
    'rating': 'மதிப்பீடு',
    'enroll_now': 'இப்போது சேருங்கள்',
    'event_name': 'நிகழ்வு பெயர்',
    'date': 'தேதி',
    'location': 'இடம்',
    'register': 'பதிவு செய்யுங்கள்',
    
    // Meditation & Yoga
    'meditation_yoga': 'தியானம் மற்றும் யோகா',
    'find_peace_balance': 'உங்கள் உள் அமைதியையும் சமநிலையையும் கண்டறியுங்கள்',
    'meditation_videos': 'தியான வீடியோக்கள்',
    'meditation_sounds': 'தியான ஒலிகள்',
    'yoga_poses': 'யோகா போஸ்கள்',
    'guided_meditation': 'வழிகாட்டப்பட்ட தியானம்',
    'breathing_exercises': 'சுவாச பயிற்சிகள்',
    'relaxation_techniques': 'ஓய்வு நுட்பங்கள்',
    'play': 'இயக்கவும்',
    'pause': 'இடைநிறுத்தவும்',
    'minutes': 'நிமிடங்கள்',
    'watch_video': 'வீடியோவைப் பாருங்கள்',
    'listen_now': 'இப்போது கேளுங்கள்',
    
    // Goals & Tracker
    'goal_tracker_title': 'இலக்கு கண்காணிப்பு',
    'track_your_progress': 'நல்வாழ்வு இலக்குகளை நோக்கிய உங்கள் முன்னேற்றத்தைக் கண்காணிக்கவும்',
    'daily_goals': 'தினசரி இலக்குகள்',
    'weekly_goals': 'வாராந்திர இலக்குகள்',
    'monthly_goals': 'மாதாந்திர இலக்குகள்',
    'add_goal': 'இலக்கு சேர்க்கவும்',
    'goal_description': 'இலக்கு விளக்கம்',
    'target_date': 'இலக்கு தேதி',
    'progress': 'முன்னேற்றம்',
    'completed': 'முடிந்தது',
    'in_progress': 'முன்னேற்றத்தில்',
    'not_started': 'தொடங்கவில்லை',
    'mark_complete': 'முடிந்ததாக குறிக்கவும்',
    'edit_goal': 'இலக்கை திருத்தவும்',
    'delete_goal': 'இலக்கை நீக்கவும்',
    
    // Personal Assistant
    'personal_assistant_title': 'தனிப்பட்ட உதவியாளர்',
    'your_ai_wellness_assistant': 'உங்கள் AI-இயங்கும் நல்வாழ்வு உதவியாளர்',
    'ask_me_anything': 'உங்கள் நல்வாழ்வு பயணத்தைப் பற்றி என்னிடம் எதையும் கேளுங்கள்',
    'suggestions': 'பரிந்துரைகள்',
    'morning_routine': 'காலை வழக்கம்',
    'stress_management': 'மன அழுத்த மேலாண்மை',
    'sleep_tips': 'தூக்க குறிப்புகள்',
    'healthy_habits': 'ஆரோக்கியமான பழக்கங்கள்',
    
    // Insights Page
    'insights_title': 'நுண்ணறிவுகள்',
    'your_wellness_journey': 'உங்கள் நல்வாழ்வு பயண நுண்ணறிவுகள்',
    'mood_trends': 'மனநிலை போக்குகள்',
    'sleep_patterns': 'தூக்க முறைகள்',
    'stress_levels': 'மன அழுத்த நிலைகள்',
    'activity_log': 'செயல்பாட்டு பதிவு',
    'weekly_summary': 'வாராந்திர சுருக்கம்',
    'monthly_summary': 'மாதாந்திர சுருக்கம்',
    'export_data': 'தரவு ஏற்றுமதி',
    'view_details': 'விவரங்களைக் காண்க',
    'last_7_days': 'கடைசி 7 நாட்கள்',
    'last_30_days': 'கடைசி 30 நாட்கள்',
    'last_90_days': 'கடைசி 90 நாட்கள்',
    'all_time': 'எல்லா நேரமும்',
    'by': 'மூலம்',
    
    // Hobbies Survey
    'discover_your_hobbies': 'உங்கள் பொழுதுபோக்குகளைக் கண்டறியவும்',
    'tell_us_interests': 'உங்கள் ஆர்வங்களைப் பற்றி எங்களிடம் கூறுங்கள், நாங்கள் சரியான செயல்பாடுகளைக் கண்டறிய உதவுவோம்',
    'what_interests_you': 'உங்களுக்கு எதில் ஆர்வம்? (பலவற்றைத் தேர்ந்தெடுக்கவும்)',
    'whats_your_budget': 'உங்கள் வரவு செலவுத் திட்டம் என்ன?',
    'when_available': 'நீங்கள் எப்போது கிடைக்கிறீர்கள்?',
    'your_location': 'உங்கள் இடம்',
    'use_current_location': 'தற்போதைய இடத்தைப் பயன்படுத்தவும்',
    'or_enter_city': 'அல்லது உங்கள் நகரத்தை கைமுறையாக உள்ளிடவும்',
    'city_placeholder': 'உங்கள் நகரத்தை உள்ளிடவும்',
    'get_recommendations': 'தனிப்பயனாக்கப்பட்ட பரிந்துரைகளைப் பெறுங்கள்',
    'select_at_least_one': 'குறைந்தது ஒரு பொழுதுபோக்கைத் தேர்ந்தெடுக்கவும்',
    'provide_location': 'தயவுசெய்து உங்கள் இடத்தை வழங்கவும்',
    'user_not_authenticated': 'பயனர் அங்கீகரிக்கப்படவில்லை',
    'geolocation_not_supported_browser': 'இந்த உலாவி ஜியோலொகேஷனை ஆதரிக்கவில்லை',
    'error_getting_location': 'இடத்தைப் பெறுவதில் பிழை',
    'day_streak': 'நாள் தொடர்!',
    'meditation_and_yoga': 'தியானம் மற்றும் யோகா',
    'hobbies_and_wanderlust': 'பொழுதுபோக்கு மற்றும் பயணம்',
    'logout': 'வெளியேறு',
    'guest_user': 'விருந்தினர் பயனர்',
    'anonymous': 'அநாமதேய',
    'secure': 'பாதுகாப்பான',
    'anonymous_session': 'அநாமதேய அமர்வு',
    'tips_for_better_practice': '💡 சிறந்த பயிற்சிக்கான குறிப்புகள்',
    'for_meditation': 'தியானத்திற்கு:',
    'for_sounds': 'ஒலிகளுக்கு:',
    'find_quiet_space': 'அமைதியான, வசதியான இடத்தைக் கண்டறியவும்',
    'start_shorter_sessions': 'குறுகிய அமர்வுகளுடன் தொடங்கவும் (5-10 நிமிடங்கள்)',
    'focus_breathing': 'உங்கள் மூச்சில் கவனம் செலுத்துங்கள்',
    'be_patient': 'உங்களுடன் பொறுமையாக இருங்கள்',
    'use_headphones': 'சிறந்த அனுபவத்திற்கு ஹெட்ஃபோன்களைப் பயன்படுத்தவும்',
    'adjust_volume': 'வசதியான நிலைகளுக்கு ஒலியளவை சரிசெய்யவும்',
    'combine_breathing': 'சுவாச பயிற்சிகளுடன் இணைக்கவும்',
    'create_practice_space': 'அர்ப்பணிக்கப்பட்ட பயிற்சி இடத்தை உருவாக்கவும்',
  },
  te: {
    // Common
    'back_to_chat': 'చాట్‌కు తిరిగి వెళ్ళు',
    'loading': 'లోడ్ అవుతోంది...',
    'error': 'లోపం',
    'success': 'విజయం',
    'cancel': 'రద్దు చేయి',
    'save': 'సేవ్ చేయి',
    'edit': 'సవరించు',
    'delete': 'తొలగించు',
    'create': 'సృష్టించు',
    'update': 'నవీకరించు',
    'yes': 'అవును',
    'no': 'కాదు',
    
    // Dashboard
    'mood_dashboard': 'మూడ్ డాష్‌బోర్డ్',
    'mental_wellness_insights': 'మీ మానసిక ఆరోగ్య అంతర్దృష్టులు ఒక చూపులో',
    'todays_wri': 'నేటి WRI',
    'band': 'బ్యాండ్',
    'insight': 'అంతర్దృష్టి',
    'band_explanation': 'బ్యాండ్ వివరణ',
    'trend': 'ట్రెండ్',
    'top_contributors': 'ప్రధాన దోహదపడేవారు',
    'wri_trend': 'WRI ట్రెండ్ (చివరి 30 ఎంట్రీలు)',
    'screening_flags': 'స్క్రీనింగ్ ఫ్లాగ్‌లు',
    'personalized_recommendations': 'వ్యక్తిగతీకరించిన సిఫార్సులు',
    'depression': 'డిప్రెషన్',
    'anxiety': 'ఆందోళన',
    'burnout_strain': 'బర్న్‌అవుట్ ఒత్తిడి',
    'social_isolation': 'సామాజిక ఏకాంతత',
    'help_readiness': 'సహాయ సంసిద్ధత',
    'per_chat_wri': 'ప్రతి చాట్ WRI',
    'daily_wri': 'రోజువారీ WRI',
    
    // Journal
    'my_journal': 'నా డైరీ',
    'journal_description': 'మీ ఆలోచనలు, భావాలు మరియు అనుభవాలను మీ వ్యక్తిగత స్థలంలో వ్రాయండి.',
    'your_entries': 'మీ ఎంట్రీలు',
    'new_entry': 'కొత్త ఎంట్రీ',
    'no_journal_entries': 'ఇంకా డైరీ ఎంట్రీలు లేవు. మీ మొదటి ఎంట్రీని సృష్టించండి!',
    'create_new_entry': 'కొత్త ఎంట్రీని సృష్టించు',
    'edit_entry': 'ఎంట్రీని సవరించు',
    'title': 'శీర్షిక',
    'content': 'విషయం',
    'enter_journal_title': 'డైరీ శీర్షికను నమోదు చేయండి...',
    'write_thoughts': 'మీ ఆలోచనలను ఇక్కడ వ్రాయండి లేదా పైన వాయిస్ రికార్డింగ్‌ను ఉపయోగించండి...',
    'characters': 'అక్షరాలు',
    'created': 'సృష్టించబడింది',
    'updated': 'నవీకరించబడింది',
    'select_journal_entry': 'చదవడానికి డైరీ ఎంట్రీని ఎంచుకోండి',
    'choose_entry_or_create': 'జాబితా నుండి ఎంట్రీని ఎంచుకోండి లేదా ప్రారంభించడానికి కొత్తది సృష్టించండి.',
    'encrypted': 'ఎన్‌క్రిప్ట్ చేయబడింది',
    'auto_clear_30min': '(30 నిమిషాల్లో ఆటో-క్లియర్)',
    'password_required': 'పాస్‌వర్డ్ అవసరం',
    'journal_created_success': 'డైరీ ఎంట్రీ విజయవంతంగా సృష్టించబడింది మరియు ఎన్‌క్రిప్ట్ చేయబడింది! మీ మూడ్ స్కోర్ మెరుగుపడుతుంది! 🎉',
    'journal_updated_success': 'డైరీ ఎంట్రీ విజయవంతంగా నవీకరించబడింది మరియు ఎన్‌క్రిప్ట్ చేయబడింది!',
    'journal_deleted_success': 'డైరీ ఎంట్రీ విజయవంతంగా తొలగించబడింది!',
    'enter_password': 'డైరీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
    'create_password': 'డైరీ పాస్‌వర్డ్‌ను సృష్టించండి',
    'encrypted_content': 'ఎన్‌క్రిప్ట్ చేయబడిన విషయం',
    'enter_password_to_view': 'ఈ డైరీ ఎంట్రీని చూడటానికి మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
    'decrypting_content': 'డైరీ విషయం డీక్రిప్ట్ చేయబడుతోంది...',
    'please_sign_in_journal': 'మీ డైరీని యాక్సెస్ చేయడానికి దయచేసి సైన్ ఇన్ చేయండి',
    
    // Chat
    'new_chat': 'కొత్త చాట్',
    'insights': 'అంతర్దృష్టులు',
    'goal_tracker': 'లక్ష్య ట్రాకర్',
    'personal_assistant': 'వ్యక్తిగత సహాయకుడు',
    'journaling': 'డైరీ రాయడం',
    'professional_help': 'వృత్తిపరమైన సహాయం',
    'dashboard': 'డాష్‌బోర్డ్',
    'chat_placeholder': 'మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి...',
    'send': 'పంపు',
    'voice_recorder': 'వాయిస్ రికార్డర్',
    'start_recording': 'రికార్డింగ్ ప్రారంభించు',
    'stop_recording': 'రికార్డింగ్ ఆపు',
    'recording': 'రికార్డ్ చేస్తోంది...',
    'transcribing': 'ట్రాన్స్‌క్రైబ్ చేస్తోంది...',
    'please_sign_in_chat': 'చాటింగ్ ప్రారంభించడానికి దయచేసి సైన్ ఇన్ చేయండి',
    
    // Professional Help
    'professional_help_title': 'వృత్తిపరమైన సహాయం',
    'find_mental_health_professionals': 'మీ సమీపంలో మానసిక ఆరోగ్య నిపుణులను కనుగొనండి',
    'search_location': 'స్థలాన్ని శోధించండి...',
    'search': 'శోధించు',
    'no_results': 'ఫలితాలు కనుగొనబడలేదు',
    'loading_professionals': 'నిపుణులను లోడ్ చేస్తోంది...',
    'please_sign_in_professional': 'వృత్తిపరమైన సహాయాన్ని యాక్సెస్ చేయడానికి దయచేసి సైన్ ఇన్ చేయండి',
    
    // Login
    'welcome': 'స్వాగతం',
    'sign_in_with_google': 'Google తో సైన్ ఇన్ చేయండి',
    'sign_in_with_github': 'GitHub తో సైన్ ఇన్ చేయండి',
    'sign_in_with_microsoft': 'Microsoft తో సైన్ ఇన్ చేయండి',
    'sign_out': 'సైన్ అవుట్',
    'mental_wellness_platform': 'మానసిక ఆరోగ్య ప్లాట్‌ఫారమ్',
    'your_mental_health_matters': 'మీ మానసిక ఆరోగ్యం ముఖ్యం. మద్దతు పొందండి, మీ మూడ్‌ను ట్రాక్ చేయండి మరియు అవసరమైనప్పుడు వృత్తిపరమైన సహాయాన్ని కనుగొనండి.',
    
    // Theme
    'light_mode': 'లైట్ మోడ్',
    'dark_mode': 'డార్క్ మోడ్',
    
    // Language
    'language': 'భాష',
    'english': 'English',
    'hindi': 'हिंदी',
    'tamil': 'தமிழ்',
    'telugu': 'తెలుగు',
    'kannada': 'ಕನ್ನಡ',
    
    // Additional keys
    'continue_anonymously': 'అనామకంగా కొనసాగించు',
    'no_account': 'ఖాతా లేదు',
    'find_nearby_help': 'సమీప సహాయాన్ని కనుగొనండి',
    'location_permission_message': 'మీ ప్రాంతంలో సమీపంలోని మానసిక ఆరోగ్య హెల్ప్‌లైన్ కేంద్రాలను కనుగొనడానికి మాకు మీ స్థానం అవసరం.',
    'getting_location': 'స్థానాన్ని పొందుతోంది...',
    'allow_location_access': 'స్థాన యాక్సెస్‌ను అనుమతించండి',
    
    // Journal specific
    'encrypted_journal_entry': 'ఎన్‌క్రిప్ట్ చేయబడిన డైరీ ఎంట్రీ',
    'create_journal_password': 'డైరీ పాస్‌వర్డ్‌ను సృష్టించండి',
    'confirm_password': 'పాస్‌వర్డ్‌ను నిర్ధారించండి',
    'password_security_note': 'మీ పాస్‌వర్డ్ ఎప్పుడూ సర్వర్‌కు పంపబడదు',
    'password_local_note': 'మీ డేటాను స్థానికంగా ఎన్‌క్రిప్ట్ చేయడానికి ఇది ఉపయోగించబడుతుంది',
    'password_remember_note': 'ఈ పాస్‌వర్డ్‌ను గుర్తుంచుకోండి - దీన్ని తిరిగి పొందలేరు!',
    
    // Date and time
    'january': 'జనవరి',
    'february': 'ఫిబ్రవరి',
    'march': 'మార్చి',
    'april': 'ఏప్రిల్',
    'may': 'మే',
    'june': 'జూన్',
    'july': 'జూలై',
    'august': 'ఆగస్టు',
    'september': 'సెప్టెంబర్',
    'october': 'అక్టోబర్',
    'november': 'నవంబర్',
    'december': 'డిసెంబర్',
    'am': 'ఉదయం',
    'pm': 'సాయంత్రం',
    
    // Chat specific
    'your_mental_wellness_companion': 'మీ మానసిక ఆరోగ్య సహచరుడు',
    'ai_powered_private_secure': 'AI-ఆధారిత • ప్రైవేట్ • సురక్షితమైనది',
    'or_continue_with': 'లేదా దీనితో కొనసాగించండి',
    'by_continuing_you_agree': 'కొనసాగించడం ద్వారా, మీరు మా',
    'privacy_policy': 'గోప్యతా విధానం',
    'and': 'మరియు',
    'terms_of_service': 'సేవా నిబంధనలు',
    'your_privacy_is_protected': 'మీ గోప్యత రక్షించబడింది',
    'new_chat_session_started': '🆕 కొత్త చాట్ సెషన్ ప్రారంభమైంది',
    'previous_insights_displayed': 'మునుపటి అంతర్దృష్టులు ప్రదర్శించబడ్డాయి కానీ AI నిర్ణయాల కోసం ఉపయోగించబడవు',
    'wellness_insights': 'ఆరోగ్య అంతర్దృష్టులు',
    'stored_insights_previous_sessions': '💾 నిల్వ చేయబడిన అంతర్దృష్టులు (మునుపటి సెషన్లు)',
    'type_your_message_here': 'మీ సందేశాన్ని ఇక్కడ టైప్ చేయండి...',
    'please_sign_in_to_start_chatting': 'చాటింగ్ ప్రారంభించడానికి దయచేసి సైన్ ఇన్ చేయండి',
    
    // Professional Help Page
    'available_247_support': 'మీ ప్రాంతంలో 24/7 మానసిక ఆరోగ్య మద్దతు అందుబాటులో ఉంది',
    'location_label': 'స్థానం',
    'call_for_help': 'సహాయం కోసం కాల్ చేయండి',
    'visit_website': 'వెబ్‌సైట్‌ను సందర్శించండి',
    'contact_number': 'సంప్రదింపు నంబర్',
    'specialties': 'ప్రత్యేకతలు',
    'available_247': '24/7 అందుబాటులో',
    'km_away': 'కి.మీ దూరంలో',
    'geolocation_not_supported': 'ఈ బ్రౌజర్ జియోలొకేషన్‌ను సపోర్ట్ చేయదు',
    'failed_to_get_location': 'స్థాన అనుమతి పొందడంలో విఫలమైంది',
    'failed_to_fetch_helplines': 'సమీపంలోని సహాయ కేంద్రాలను తీసుకురావడంలో విఫలమైంది',
    
    // Hobbies Pages
    'hobbies_recommendations': 'అభిరుచుల సిఫార్సులు',
    'discover_new_hobbies': 'మీ కోసం రూపొందించిన కొత్త అభిరుచులను కనుగొనండి',
    'recommended_for_you': 'మీ కోసం సిఫార్సు చేయబడింది',
    'online_courses': 'ఆన్‌లైన్ కోర్సులు',
    'local_events': 'స్థానిక కార్యక్రమాలు',
    'hobby_name': 'అభిరుచి పేరు',
    'difficulty_level': 'కష్ట స్థాయి',
    'time_required': 'అవసరమైన సమయం',
    'benefits': 'ప్రయోజనాలు',
    'get_started': 'ప్రారంభించండి',
    'course_title': 'కోర్సు శీర్షిక',
    'platform': 'ప్లాట్‌ఫారమ్',
    'duration': 'వ్యవధి',
    'rating': 'రేటింగ్',
    'enroll_now': 'ఇప్పుడు నమోదు చేసుకోండి',
    'event_name': 'కార్యక్రమం పేరు',
    'date': 'తేదీ',
    'location': 'స్థానం',
    'register': 'నమోదు చేయండి',
    
    // Meditation & Yoga
    'meditation_yoga': 'ధ్యానం మరియు యోగా',
    'find_peace_balance': 'మీ అంతర్గత శాంతి మరియు సమతుల్యతను కనుగొనండి',
    'meditation_videos': 'ధ్యాన వీడియోలు',
    'meditation_sounds': 'ధ్యాన ధ్వనులు',
    'yoga_poses': 'యోగా పోజ్‌లు',
    'guided_meditation': 'మార్గదర్శక ధ్యానం',
    'breathing_exercises': 'శ్వాస వ్యాయామాలు',
    'relaxation_techniques': 'విశ్రాంతి పద్ధతులు',
    'play': 'ప్లే',
    'pause': 'పాజ్',
    'minutes': 'నిమిషాలు',
    'watch_video': 'వీడియో చూడండి',
    'listen_now': 'ఇప్పుడు వినండి',
    
    // Goals & Tracker
    'goal_tracker_title': 'లక్ష్య ట్రాకర్',
    'track_your_progress': 'ఆరోగ్య లక్ష్యాల వైపు మీ పురోగతిని ట్రాక్ చేయండి',
    'daily_goals': 'రోజువారీ లక్ష్యాలు',
    'weekly_goals': 'వారపు లక్ష్యాలు',
    'monthly_goals': 'నెలవారీ లక్ష్యాలు',
    'add_goal': 'లక్ష్యం జోడించండి',
    'goal_description': 'లక్ష్యం వివరణ',
    'target_date': 'లక్ష్య తేదీ',
    'progress': 'పురోగతి',
    'completed': 'పూర్తయింది',
    'in_progress': 'పురోగతిలో',
    'not_started': 'ప్రారంభించలేదు',
    'mark_complete': 'పూర్తయినట్లు గుర్తించండి',
    'edit_goal': 'లక్ష్యాన్ని సవరించండి',
    'delete_goal': 'లక్ష్యాన్ని తొలగించండి',
    
    // Personal Assistant
    'personal_assistant_title': 'వ్యక్తిగత సహాయకుడు',
    'your_ai_wellness_assistant': 'మీ AI-ఆధారిత ఆరోగ్య సహాయకుడు',
    'ask_me_anything': 'మీ ఆరోగ్య ప్రయాణం గురించి నన్ను ఏదైనా అడగండి',
    'suggestions': 'సూచనలు',
    'morning_routine': 'ఉదయ దినచర్య',
    'stress_management': 'ఒత్తిడి నిర్వహణ',
    'sleep_tips': 'నిద్ర చిట్కాలు',
    'healthy_habits': 'ఆరోగ్యకరమైన అలవాట్లు',
    
    // Insights Page
    'insights_title': 'అంతర్దృష్టులు',
    'your_wellness_journey': 'మీ ఆరోగ్య ప్రయాణ అంతర్దృష్టులు',
    'mood_trends': 'మూడ్ ట్రెండ్స్',
    'sleep_patterns': 'నిద్ర నమూనాలు',
    'stress_levels': 'ఒత్తిడి స్థాయిలు',
    'activity_log': 'కార్యకలాపాల లాగ్',
    'weekly_summary': 'వారపు సారాంశం',
    'monthly_summary': 'నెలవారీ సారాంశం',
    'export_data': 'డేటా ఎగుమతి',
    'view_details': 'వివరాలను చూడండి',
    'last_7_days': 'చివరి 7 రోజులు',
    'last_30_days': 'చివరి 30 రోజులు',
    'last_90_days': 'చివరి 90 రోజులు',
    'all_time': 'అన్ని సమయాలు',
    'by': 'ద్వారా',
    
    // Hobbies Survey
    'discover_your_hobbies': 'మీ అభిరుచులను కనుగొనండి',
    'tell_us_interests': 'మీ ఆసక్తుల గురించి మాకు చెప్పండి మరియు సరైన కార్యకలాపాలను కనుగొనడంలో మేము మీకు సహాయం చేస్తాము',
    'what_interests_you': 'మీకు దేనిపై ఆసక్తి ఉంది? (బహుళ ఎంపిక చేయండి)',
    'whats_your_budget': 'మీ బడ్జెట్ ఎంత?',
    'when_available': 'మీరు ఎప్పుడు అందుబాటులో ఉన్నారు?',
    'your_location': 'మీ స్థానం',
    'use_current_location': 'ప్రస్తుత స్థానాన్ని ఉపయోగించండి',
    'or_enter_city': 'లేదా మీ నగరాన్ని మాన్యువల్‌గా నమోదు చేయండి',
    'city_placeholder': 'మీ నగరాన్ని నమోదు చేయండి',
    'get_recommendations': 'వ్యక్తిగత సిఫార్సులను పొందండి',
    'select_at_least_one': 'దయచేసి కనీసం ఒక అభిరుచిని ఎంచుకోండి',
    'provide_location': 'దయచేసి మీ స్థానాన్ని అందించండి',
    'user_not_authenticated': 'వినియోగదారు ప్రమాణీకరించబడలేదు',
    'geolocation_not_supported_browser': 'ఈ బ్రౌజర్ జియోలొకేషన్‌కు మద్దతు ఇవ్వదు',
    'error_getting_location': 'స్థానాన్ని పొందడంలో లోపం',
    'day_streak': 'రోజుల సరళి!',
    'meditation_and_yoga': 'ధ్యానం మరియు యోగా',
    'hobbies_and_wanderlust': 'అభిరుచులు మరియు యాత్ర',
    'logout': 'లాగౌట్',
    'guest_user': 'అతిథి వినియోగదారు',
    'anonymous': 'అనామక',
    'secure': 'సురక్షిత',
    'anonymous_session': 'అనామక సెషన్',
    'tips_for_better_practice': '💡 మెరుగైన అభ్యాసం కోసం చిట్కాలు',
    'for_meditation': 'ధ్యానం కోసం:',
    'for_sounds': 'శబ్దాల కోసం:',
    'find_quiet_space': 'నిశ్శబ్ద, సౌకర్యవంతమైన స్థలాన్ని కనుగొనండి',
    'start_shorter_sessions': 'చిన్న సెషన్లతో ప్రారంభించండి (5-10 నిమిషాలు)',
    'focus_breathing': 'మీ శ్వాసపై దృష్టి పెట్టండి',
    'be_patient': 'మీతో సహనంగా ఉండండి',
    'use_headphones': 'మెరుగైన అనుభవం కోసం హెడ్‌ఫోన్‌లను ఉపయోగించండి',
    'adjust_volume': 'సౌకర్యవంతమైన స్థాయిలకు వాల్యూమ్‌ను సర్దుబాటు చేయండి',
    'combine_breathing': 'శ్వాస వ్యాయామాలతో కలపండి',
    'create_practice_space': 'అంకితమైన అభ్యాస స్థలాన్ని సృష్టించండి',
  },
  kn: {
    // Common
    'back_to_chat': 'ಚಾಟ್‌ಗೆ ಹಿಂತಿರುಗಿ',
    'loading': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'error': 'ದೋಷ',
    'success': 'ಯಶಸ್ಸು',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'save': 'ಉಳಿಸಿ',
    'edit': 'ಸಂಪಾದಿಸಿ',
    'delete': 'ಅಳಿಸಿ',
    'create': 'ರಚಿಸಿ',
    'update': 'ನವೀಕರಿಸಿ',
    'yes': 'ಹೌದು',
    'no': 'ಇಲ್ಲ',
    
    // Dashboard
    'mood_dashboard': 'ಮೂಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'mental_wellness_insights': 'ನಿಮ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಒಳನೋಟಗಳು ಒಂದು ನೋಟದಲ್ಲಿ',
    'todays_wri': 'ಇಂದಿನ WRI',
    'band': 'ಬ್ಯಾಂಡ್',
    'insight': 'ಒಳನೋಟ',
    'band_explanation': 'ಬ್ಯಾಂಡ್ ವಿವರಣೆ',
    'trend': 'ಟ್ರೆಂಡ್',
    'top_contributors': 'ಪ್ರಮುಖ ಕೊಡುಗೆದಾರರು',
    'wri_trend': 'WRI ಟ್ರೆಂಡ್ (ಕೊನೆಯ 30 ನಮೂದುಗಳು)',
    'screening_flags': 'ಸ್ಕ್ರೀನಿಂಗ್ ಫ್ಲ್ಯಾಗ್‌ಗಳು',
    'personalized_recommendations': 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಶಿಫಾರಸುಗಳು',
    'depression': 'ಖಿನ್ನತೆ',
    'anxiety': 'ಆತಂಕ',
    'burnout_strain': 'ಬರ್ನ್‌ಔಟ್ ಒತ್ತಡ',
    'social_isolation': 'ಸಾಮಾಜಿಕ ಪ್ರತ್ಯೇಕತೆ',
    'help_readiness': 'ಸಹಾಯ ಸಿದ್ಧತೆ',
    'per_chat_wri': 'ಪ್ರತಿ ಚಾಟ್ WRI',
    'daily_wri': 'ದೈನಂದಿನ WRI',
    
    // Journal
    'my_journal': 'ನನ್ನ ಡೈರಿ',
    'journal_description': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳು, ಭಾವನೆಗಳು ಮತ್ತು ಅನುಭವಗಳನ್ನು ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಸ್ಥಳದಲ್ಲಿ ಬರೆಯಿರಿ.',
    'your_entries': 'ನಿಮ್ಮ ನಮೂದುಗಳು',
    'new_entry': 'ಹೊಸ ನಮೂದು',
    'no_journal_entries': 'ಇನ್ನೂ ಡೈರಿ ನಮೂದುಗಳಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ನಮೂದನ್ನು ರಚಿಸಿ!',
    'create_new_entry': 'ಹೊಸ ನಮೂದನ್ನು ರಚಿಸಿ',
    'edit_entry': 'ನಮೂದನ್ನು ಸಂಪಾದಿಸಿ',
    'title': 'ಶೀರ್ಷಿಕೆ',
    'content': 'ವಿಷಯ',
    'enter_journal_title': 'ಡೈರಿ ಶೀರ್ಷಿಕೆಯನ್ನು ನಮೂದಿಸಿ...',
    'write_thoughts': 'ನಿಮ್ಮ ಆಲೋಚನೆಗಳನ್ನು ಇಲ್ಲಿ ಬರೆಯಿರಿ ಅಥವಾ ಮೇಲೆ ಧ್ವನಿ ರೆಕಾರ್ಡಿಂಗ್ ಅನ್ನು ಬಳಸಿ...',
    'characters': 'ಅಕ್ಷರಗಳು',
    'created': 'ರಚಿಸಲಾಗಿದೆ',
    'updated': 'ನವೀಕರಿಸಲಾಗಿದೆ',
    'select_journal_entry': 'ಓದಲು ಡೈರಿ ನಮೂದನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'choose_entry_or_create': 'ಪಟ್ಟಿಯಿಂದ ನಮೂದನ್ನು ಆಯ್ಕೆಮಾಡಿ ಅಥವಾ ಪ್ರಾರಂಭಿಸಲು ಹೊಸದನ್ನು ರಚಿಸಿ.',
    'encrypted': 'ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ',
    'auto_clear_30min': '(30 ನಿಮಿಷಗಳಲ್ಲಿ ಆಟೋ-ಕ್ಲಿಯರ್)',
    'password_required': 'ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯವಿದೆ',
    'journal_created_success': 'ಡೈರಿ ನಮೂದನ್ನು ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ! ನಿಮ್ಮ ಮೂಡ್ ಸ್ಕೋರ್ ಸುಧಾರಿಸುತ್ತದೆ! 🎉',
    'journal_updated_success': 'ಡೈರಿ ನಮೂದನ್ನು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ ಮತ್ತು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗಿದೆ!',
    'journal_deleted_success': 'ಡೈರಿ ನಮೂದನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಅಳಿಸಲಾಗಿದೆ!',
    'enter_password': 'ಡೈರಿ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'create_password': 'ಡೈರಿ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ',
    'encrypted_content': 'ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ ವಿಷಯ',
    'enter_password_to_view': 'ಈ ಡೈರಿ ನಮೂದನ್ನು ವೀಕ್ಷಿಸಲು ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ನಮೂದಿಸಿ',
    'decrypting_content': 'ಡೈರಿ ವಿಷಯವನ್ನು ಡೀಕ್ರಿಪ್ಟ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'please_sign_in_journal': 'ನಿಮ್ಮ ಡೈರಿಯನ್ನು ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    
    // Chat
    'new_chat': 'ಹೊಸ ಚಾಟ್',
    'insights': 'ಒಳನೋಟಗಳು',
    'goal_tracker': 'ಗುರಿ ಟ್ರ್ಯಾಕರ್',
    'personal_assistant': 'ವೈಯಕ್ತಿಕ ಸಹಾಯಕ',
    'journaling': 'ಡೈರಿ ಬರೆಯುವುದು',
    'professional_help': 'ವೃತ್ತಿಪರ ಸಹಾಯ',
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'chat_placeholder': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    'send': 'ಕಳುಹಿಸಿ',
    'voice_recorder': 'ವಾಯ್ಸ್ ರೆಕಾರ್ಡರ್',
    'start_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    'stop_recording': 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    'recording': 'ರೆಕಾರ್ಡ್ ಮಾಡುತ್ತಿದೆ...',
    'transcribing': 'ಲಿಪಿಯಾಗುತ್ತಿದೆ...',
    'please_sign_in_chat': 'ಚಾಟಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    
    // Professional Help
    'professional_help_title': 'ವೃತ್ತಿಪರ ಸಹಾಯ',
    'find_mental_health_professionals': 'ನಿಮ್ಮ ಹತ್ತಿರ ಮಾನಸಿಕ ಆರೋಗ್ಯ ವೃತ್ತಿಪರರನ್ನು ಹುಡುಕಿ',
    'search_location': 'ಸ್ಥಳವನ್ನು ಹುಡುಕಿ...',
    'search': 'ಹುಡುಕಿ',
    'no_results': 'ಫಲಿತಾಂಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'loading_professionals': 'ವೃತ್ತಿಪರರನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'please_sign_in_professional': 'ವೃತ್ತಿಪರ ಸಹಾಯವನ್ನು ಪ್ರವೇಶಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    
    // Login
    'welcome': 'ಸ್ವಾಗತ',
    'sign_in_with_google': 'Google ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'sign_in_with_github': 'GitHub ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'sign_in_with_microsoft': 'Microsoft ನೊಂದಿಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'sign_out': 'ಸೈನ್ ಔಟ್',
    'mental_wellness_platform': 'ಮಾನಸಿಕ ಆರೋಗ್ಯ ವೇದಿಕೆ',
    'your_mental_health_matters': 'ನಿಮ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಮುಖ್ಯವಾಗಿದೆ. ಬೆಂಬಲವನ್ನು ಪಡೆಯಿರಿ, ನಿಮ್ಮ ಮೂಡ್ ಅನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಅಗತ್ಯವಿದ್ದಾಗ ವೃತ್ತಿಪರ ಸಹಾಯವನ್ನು ಹುಡುಕಿ.',
    
    // Theme
    'light_mode': 'ಲೈಟ್ ಮೋಡ್',
    'dark_mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
    
    // Language
    'language': 'ಭಾಷೆ',
    'english': 'English',
    'hindi': 'हिंदी',
    'tamil': 'தமிழ்',
    'telugu': 'తెలుగు',
    'kannada': 'ಕನ್ನಡ',
    
    // Additional keys
    'continue_anonymously': 'ಅನಾಮಧೇಯವಾಗಿ ಮುಂದುವರಿಸಿ',
    'no_account': 'ಖಾತೆ ಇಲ್ಲ',
    'find_nearby_help': 'ಹತ್ತಿರದ ಸಹಾಯವನ್ನು ಹುಡುಕಿ',
    'location_permission_message': 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಹತ್ತಿರದ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಹೆಲ್ಪ್‌ಲೈನ್ ಕೇಂದ್ರಗಳನ್ನು ಹುಡುಕಲು ನಮಗೆ ನಿಮ್ಮ ಸ್ಥಳ ಅಗತ್ಯವಿದೆ.',
    'getting_location': 'ಸ್ಥಳವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    'allow_location_access': 'ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ಅನುಮತಿಸಿ',
    
    // Journal specific
    'encrypted_journal_entry': 'ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಿದ ಡೈರಿ ನಮೂದು',
    'create_journal_password': 'ಡೈರಿ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ',
    'confirm_password': 'ಪಾಸ್‌ವರ್ಡ್ ದೃಢೀಕರಿಸಿ',
    'password_security_note': 'ನಿಮ್ಮ ಪಾಸ್‌ವರ್ಡ್ ಎಂದಿಗೂ ಸರ್ವರ್‌ಗೆ ಕಳುಹಿಸಲಾಗುವುದಿಲ್ಲ',
    'password_local_note': 'ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಸ್ಥಳೀಯವಾಗಿ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಮಾಡಲು ಇದನ್ನು ಬಳಸಲಾಗುತ್ತದೆ',
    'password_remember_note': 'ಈ ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ನೆನಪಿಡಿ - ಅದನ್ನು ಮರುಪಡೆಯಲಾಗುವುದಿಲ್ಲ!',
    
    // Date and time
    'january': 'ಜನವರಿ',
    'february': 'ಫೆಬ್ರವರಿ',
    'march': 'ಮಾರ್ಚ್',
    'april': 'ಏಪ್ರಿಲ್',
    'may': 'ಮೇ',
    'june': 'ಜೂನ್',
    'july': 'ಜುಲೈ',
    'august': 'ಆಗಸ್ಟ್',
    'september': 'ಸೆಪ್ಟೆಂಬರ್',
    'october': 'ಅಕ್ಟೋಬರ್',
    'november': 'ನವೆಂಬರ್',
    'december': 'ಡಿಸೆಂಬರ್',
    'am': 'ಬೆಳಿಗ್ಗೆ',
    'pm': 'ಸಂಜೆ',
    
    // Chat specific
    'your_mental_wellness_companion': 'ನಿಮ್ಮ ಮಾನಸಿಕ ಆರೋಗ್ಯ ಸಹಚರ',
    'ai_powered_private_secure': 'AI-ಚಾಲಿತ • ಖಾಸಗಿ • ಸುರಕ್ಷಿತ',
    'or_continue_with': 'ಅಥವಾ ಇದರೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    'by_continuing_you_agree': 'ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ',
    'privacy_policy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
    'and': 'ಮತ್ತು',
    'terms_of_service': 'ಸೇವಾ ನಿಯಮಗಳು',
    'your_privacy_is_protected': 'ನಿಮ್ಮ ಗೌಪ್ಯತೆ ರಕ್ಷಿಸಲಾಗಿದೆ',
    'new_chat_session_started': '🆕 ಹೊಸ ಚಾಟ್ ಸೆಷನ್ ಪ್ರಾರಂಭವಾಗಿದೆ',
    'previous_insights_displayed': 'ಹಿಂದಿನ ಒಳನೋಟಗಳನ್ನು ಪ್ರದರ್ಶಿಸಲಾಗಿದೆ ಆದರೆ AI ನಿರ್ಧಾರಗಳಿಗೆ ಬಳಸಲಾಗಿಲ್ಲ',
    'wellness_insights': 'ಆರೋಗ್ಯ ಒಳನೋಟಗಳು',
    'stored_insights_previous_sessions': '💾 ಸಂಗ್ರಹಿಸಿದ ಒಳನೋಟಗಳು (ಹಿಂದಿನ ಸೆಷನ್‌ಗಳು)',
    'type_your_message_here': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...',
    'please_sign_in_to_start_chatting': 'ಚಾಟಿಂಗ್ ಪ್ರಾರಂಭಿಸಲು ದಯವಿಟ್ಟು ಸೈನ್ ಇನ್ ಮಾಡಿ',
    
    // Professional Help Page
    'available_247_support': 'ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ 24/7 ಮಾನಸಿಕ ಆರೋಗ್ಯ ಬೆಂಬಲ ಲಭ್ಯವಿದೆ',
    'location_label': 'ಸ್ಥಳ',
    'call_for_help': 'ಸಹಾಯಕ್ಕಾಗಿ ಕರೆ ಮಾಡಿ',
    'visit_website': 'ವೆಬ್‌ಸೈಟ್‌ಗೆ ಭೇಟಿ ನೀಡಿ',
    'contact_number': 'ಸಂಪರ್ಕ ಸಂಖ್ಯೆ',
    'specialties': 'ವಿಶೇಷತೆಗಳು',
    'available_247': '24/7 ಲಭ್ಯವಿದೆ',
    'km_away': 'ಕಿ.ಮೀ ದೂರದಲ್ಲಿ',
    'geolocation_not_supported': 'ಈ ಬ್ರೌಸರ್ ಜಿಯೋಲೊಕೇಶನ್ ಅನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ',
    'failed_to_get_location': 'ಸ್ಥಳ ಅನುಮತಿ ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ',
    'failed_to_fetch_helplines': 'ಹತ್ತಿರದ ಸಹಾಯ ಕೇಂದ್ರಗಳನ್ನು ಪಡೆಯಲು ವಿಫಲವಾಗಿದೆ',
    
    // Hobbies Pages
    'hobbies_recommendations': 'ಹವ್ಯಾಸ ಶಿಫಾರಸುಗಳು',
    'discover_new_hobbies': 'ನಿಮಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಿದ ಹೊಸ ಹವ್ಯಾಸಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ',
    'recommended_for_you': 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
    'online_courses': 'ಆನ್‌ಲೈನ್ ಕೋರ್ಸ್‌ಗಳು',
    'local_events': 'ಸ್ಥಳೀಯ ಘಟನೆಗಳು',
    'hobby_name': 'ಹವ್ಯಾಸ ಹೆಸರು',
    'difficulty_level': 'ಕಷ್ಟದ ಮಟ್ಟ',
    'time_required': 'ಅಗತ್ಯವಿರುವ ಸಮಯ',
    'benefits': 'ಪ್ರಯೋಜನಗಳು',
    'get_started': 'ಪ್ರಾರಂಭಿಸಿ',
    'course_title': 'ಕೋರ್ಸ್ ಶೀರ್ಷಿಕೆ',
    'platform': 'ವೇದಿಕೆ',
    'duration': 'ಅವಧಿ',
    'rating': 'ರೇಟಿಂಗ್',
    'enroll_now': 'ಈಗ ದಾಖಲಾತಿ ಮಾಡಿ',
    'event_name': 'ಘಟನೆ ಹೆಸರು',
    'date': 'ದಿನಾಂಕ',
    'location': 'ಸ್ಥಳ',
    'register': 'ನೋಂದಣಿ ಮಾಡಿ',
    
    // Meditation & Yoga
    'meditation_yoga': 'ಧ್ಯಾನ ಮತ್ತು ಯೋಗ',
    'find_peace_balance': 'ನಿಮ್ಮ ಆಂತರಿಕ ಶಾಂತಿ ಮತ್ತು ಸಮತೋಲನವನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    'meditation_videos': 'ಧ್ಯಾನ ವೀಡಿಯೊಗಳು',
    'meditation_sounds': 'ಧ್ಯಾನ ಶಬ್ದಗಳು',
    'yoga_poses': 'ಯೋಗ ಭಂಗಿಗಳು',
    'guided_meditation': 'ಮಾರ್ಗದರ್ಶಿತ ಧ್ಯಾನ',
    'breathing_exercises': 'ಉಸಿರಾಟದ ವ್ಯಾಯಾಮಗಳು',
    'relaxation_techniques': 'ವಿಶ್ರಾಂತಿ ತಂತ್ರಗಳು',
    'play': 'ಪ್ಲೇ',
    'pause': 'ವಿರಾಮ',
    'minutes': 'ನಿಮಿಷಗಳು',
    'watch_video': 'ವೀಡಿಯೊ ವೀಕ್ಷಿಸಿ',
    'listen_now': 'ಈಗ ಕೇಳಿ',
    
    // Goals & Tracker
    'goal_tracker_title': 'ಗುರಿ ಟ್ರ್ಯಾಕರ್',
    'track_your_progress': 'ಆರೋಗ್ಯ ಗುರಿಗಳ ಕಡೆಗೆ ನಿಮ್ಮ ಪ್ರಗತಿಯನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ',
    'daily_goals': 'ದೈನಂದಿನ ಗುರಿಗಳು',
    'weekly_goals': 'ಸಾಪ್ತಾಹಿಕ ಗುರಿಗಳು',
    'monthly_goals': 'ಮಾಸಿಕ ಗುರಿಗಳು',
    'add_goal': 'ಗುರಿಯನ್ನು ಸೇರಿಸಿ',
    'goal_description': 'ಗುರಿ ವಿವರಣೆ',
    'target_date': 'ಗುರಿ ದಿನಾಂಕ',
    'progress': 'ಪ್ರಗತಿ',
    'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
    'not_started': 'ಪ್ರಾರಂಭವಾಗಿಲ್ಲ',
    'mark_complete': 'ಪೂರ್ಣಗೊಂಡಿದೆ ಎಂದು ಗುರುತಿಸಿ',
    'edit_goal': 'ಗುರಿಯನ್ನು ಸಂಪಾದಿಸಿ',
    'delete_goal': 'ಗುರಿಯನ್ನು ಅಳಿಸಿ',
    
    // Personal Assistant
    'personal_assistant_title': 'ವೈಯಕ್ತಿಕ ಸಹಾಯಕ',
    'your_ai_wellness_assistant': 'ನಿಮ್ಮ AI-ಚಾಲಿತ ಆರೋಗ್ಯ ಸಹಾಯಕ',
    'ask_me_anything': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣದ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನನ್ನಾದರೂ ಕೇಳಿ',
    'suggestions': 'ಸಲಹೆಗಳು',
    'morning_routine': 'ಬೆಳಗಿನ ದಿನಚರಿ',
    'stress_management': 'ಒತ್ತಡ ನಿರ್ವಹಣೆ',
    'sleep_tips': 'ನಿದ್ರೆಯ ಸಲಹೆಗಳು',
    'healthy_habits': 'ಆರೋಗ್ಯಕರ ಅಭ್ಯಾಸಗಳು',
    
    // Insights Page
    'insights_title': 'ಒಳನೋಟಗಳು',
    'your_wellness_journey': 'ನಿಮ್ಮ ಆರೋಗ್ಯ ಪ್ರಯಾಣ ಒಳನೋಟಗಳು',
    'mood_trends': 'ಮೂಡ್ ಟ್ರೆಂಡ್ಸ್',
    'sleep_patterns': 'ನಿದ್ರೆ ಮಾದರಿಗಳು',
    'stress_levels': 'ಒತ್ತಡ ಮಟ್ಟಗಳು',
    'activity_log': 'ಚಟುವಟಿಕೆ ಲಾಗ್',
    'weekly_summary': 'ಸಾಪ್ತಾಹಿಕ ಸಾರಾಂಶ',
    'monthly_summary': 'ಮಾಸಿಕ ಸಾರಾಂಶ',
    'export_data': 'ಡೇಟಾ ರಫ್ತು',
    'view_details': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'last_7_days': 'ಕೊನೆಯ 7 ದಿನಗಳು',
    'last_30_days': 'ಕೊನೆಯ 30 ದಿನಗಳು',
    'last_90_days': 'ಕೊನೆಯ 90 ದಿನಗಳು',
    'all_time': 'ಎಲ್ಲಾ ಸಮಯ',
    'by': 'ಮೂಲಕ',
    
    // Hobbies Survey
    'discover_your_hobbies': 'ನಿಮ್ಮ ಹವ್ಯಾಸಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ',
    'tell_us_interests': 'ನಿಮ್ಮ ಆಸಕ್ತಿಗಳ ಬಗ್ಗೆ ನಮಗೆ ತಿಳಿಸಿ ಮತ್ತು ಸರಿಯಾದ ಚಟುವಟಿಕೆಗಳನ್ನು ಕಂಡುಹಿಡಿಯಲು ನಾವು ನಿಮಗೆ ಸಹಾಯ ಮಾಡುತ್ತೇವೆ',
    'what_interests_you': 'ನಿಮಗೆ ಯಾವುದರಲ್ಲಿ ಆಸಕ್ತಿ ಇದೆ? (ಬಹು ಆಯ್ಕೆ ಮಾಡಿ)',
    'whats_your_budget': 'ನಿಮ್ಮ ಬಜೆಟ್ ಎಷ್ಟು?',
    'when_available': 'ನೀವು ಯಾವಾಗ ಲಭ್ಯವಿದ್ದೀರಿ?',
    'your_location': 'ನಿಮ್ಮ ಸ್ಥಳ',
    'use_current_location': 'ಪ್ರಸ್ತುತ ಸ್ಥಳವನ್ನು ಬಳಸಿ',
    'or_enter_city': 'ಅಥವಾ ನಿಮ್ಮ ನಗರವನ್ನು ಹಸ್ತಚಾಲಿತವಾಗಿ ನಮೂದಿಸಿ',
    'city_placeholder': 'ನಿಮ್ಮ ನಗರವನ್ನು ನಮೂದಿಸಿ',
    'get_recommendations': 'ವೈಯಕ್ತಿಕ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'select_at_least_one': 'ದಯವಿಟ್ಟು ಕನಿಷ್ಠ ಒಂದು ಹವ್ಯಾಸವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'provide_location': 'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಒದಗಿಸಿ',
    'user_not_authenticated': 'ಬಳಕೆದಾರರು ದೃಢೀಕರಿಸಲ್ಪಟ್ಟಿಲ್ಲ',
    'geolocation_not_supported_browser': 'ಈ ಬ್ರೌಸರ್ ಜಿಯೋಲೊಕೇಶನ್ ಅನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ',
    'error_getting_location': 'ಸ್ಥಳವನ್ನು ಪಡೆಯುವಲ್ಲಿ ದೋಷ',
    'day_streak': 'ದಿನದ ಸರಣಿ!',
    'meditation_and_yoga': 'ಧ್ಯಾನ ಮತ್ತು ಯೋಗ',
    'hobbies_and_wanderlust': 'ಹವ್ಯಾಸಗಳು ಮತ್ತು ಪ್ರಯಾಣ',
    'logout': 'ಲಾಗೌಟ್',
    'guest_user': 'ಅತಿಥಿ ಬಳಕೆದಾರ',
    'anonymous': 'ಅನಾಮಧೇಯ',
    'secure': 'ಸುರಕ್ಷಿತ',
    'anonymous_session': 'ಅನಾಮಧೇಯ ಸೆಷನ್',
    'tips_for_better_practice': '💡 ಉತ್ತಮ ಅಭ್ಯಾಸಕ್ಕಾಗಿ ಸಲಹೆಗಳು',
    'for_meditation': 'ಧ್ಯಾನಕ್ಕಾಗಿ:',
    'for_sounds': 'ಶಬ್ದಗಳಿಗಾಗಿ:',
    'find_quiet_space': 'ಶಾಂತ, ಆರಾಮದಾಯಕ ಸ್ಥಳವನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    'start_shorter_sessions': 'ಕಿರು ಸೆಷನ್‌ಗಳೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಿ (5-10 ನಿಮಿಷಗಳು)',
    'focus_breathing': 'ನಿಮ್ಮ ಉಸಿರಾಟದ ಮೇಲೆ ಗಮನ ಹರಿಸಿ',
    'be_patient': 'ನಿಮ್ಮೊಂದಿಗೆ ತಾಳ್ಮೆ ತಳೆಯಿರಿ',
    'use_headphones': 'ಉತ್ತಮ ಅನುಭವಕ್ಕಾಗಿ ಹೆಡ್‌ಫೋನ್‌ಗಳನ್ನು ಬಳಸಿ',
    'adjust_volume': 'ಆರಾಮದಾಯಕ ಮಟ್ಟಗಳಿಗೆ ವಾಲ್ಯೂಮ್ ಅನ್ನು ಸರಿಹೊಂದಿಸಿ',
    'combine_breathing': 'ಉಸಿರಾಟದ ವ್ಯಾಯಾಮಗಳೊಂದಿಗೆ ಸಂಯೋಜಿಸಿ',
    'create_practice_space': 'ಸಮರ್ಪಿತ ಅಭ್ಯಾಸ ಸ್ಥಳವನ್ನು ರಚಿಸಿ',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('selectedLanguage') as Language;
    if (savedLanguage && ['en', 'hi', 'ta', 'te', 'kn'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when changed
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('selectedLanguage', lang);
  };

  // Translation function
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
